MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  BACKBONE:
    NAME: "build_fcos_resnet_nofpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS: 
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEPTH: 50
  NOFPN:  
    IN_FEATURES: ["res3", "res4", "res5"]
    #NORM: "SyncBN" 
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
DATASETS:
  TRAIN: ("uavdt_train_cocostyle","uavdt_val_cocostyle")
  TEST: ("uavdt_test_cocostyle",)  
SOLVER:
  IMS_PER_BATCH: 8 #FCOS 8 is best
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 100000
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 600
  MAX_SIZE_TEST: 600
  MIN_SIZE_TEST: 600
